sonar.projectKey=ClaudineRas02_pop-quizz-linux-back-end
sonar.organization=claudineras02

sonar.sources=src
sonar.tests=tests

sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info